language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master
before_install:
  - npm install -g firebase-tools
  - npm install -g mocha
  - npm install -g hexo
install:
  - npm install
script:
  - hexo generate
  - npm run create-project-folders
  - npm run copy
  - hexo serve -s
  - gulp revall
  - npm run test
after_success:
  - firebase deploy --token $FIREBASE_TOKEN