language: node_js
node_js:
  - "8"
branches:
  only:
    - master
before_install:
  - npm install -g firebase-tools
  - npm install -g mocha
  - npm install -g hexo
install:
  - npm install
script:
  - hexo generate
after_success:
  - firebase deploy --token $FIREBASE_TOKEN